api/urls.py
from django.conf.urls import patterns, url
from api import views

urlpatterns = patterns('api.views',
    url(r'^account/$', views.account, name = 'account'),
    url(r'^rides/$', views.rides, name = 'rides'),
    url(r'^test/$', views.test, name = 'test')
)

dashboard/urls.py
from django.conf.urls import patterns, url
from dashboard import views

urlpatterns = patterns('dashboard.views',
    url(r'^$', views.dashboard, name = 'dashboard'),
    url(r'^team/stats/$', views.all_riders, name = 'team_stats'),
    url(r'^riders/(?P<rider>\d+)$', views.dashboard, name = 'dashboard'),
    url(r'^login/$', views.enter_gate, name = 'login'),
    url(r'^logout/$', views.exit_gate, name = 'logout'),
    url(r'^profile/change_password/$', views.change_password, name = 'change_password'),
    url(r'^first_login/$', views.first_login, name = 'first_login'),
)

fitness/urls.py
from django.conf.urls import patterns, url
from fitness import views

urlpatterns = patterns('fitness.views',
    url(r'^rides/$', views.rides, name = 'rides'),
    url(r'^log/$', views.log, name = 'log')
)

t4krms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('dashboard.urls', namespace = "dashboard")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fitness/', include('fitness.urls', namespace = "fitness")),
    url(r'^tools/', include('links.urls', namespace = "links")),
    url(r'^adminlinks/', include('adminlinks.urls', namespace = "adminlinks")),
    url(r'^api/', include('api.urls', namespace = "api"))
)

templates/dashboard/urls.py
from django.conf.urls import patterns, url
from links import views

urlpatterns = patterns('links.views',
    url(r'^link/settings/$', views.settings, name = 'settings'),
    url(r'^link/stats/$', views.stats, name = 'stats'),
)

dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.db.models import Sum, Avg
from django.core.exceptions import ObjectDoesNotExist
from datetime import datetime, date
import time
from decimal import Decimal
from riders.models import Teammate
from fitness.models import Ride
from links.models import Link


def all_riders(request):
    #TODO maybe we should write a test
    total_miles = Ride.objects.all().aggregate(Sum('miles'))['miles__sum']
    total_time = Ride.objects.all().aggregate(Sum('duration'))['duration__sum']

    #TODO: doing two database joins, this is probably not a good idea in general
    riders = Teammate.objects
    riders = riders.annotate(total_miles = Sum('ride__miles'))
    riders = riders.annotate(total_time = Sum('ride__duration'))
    riders = riders.order_by('-total_miles')
    context = {
        'riders' : riders,
        'total_miles' : total_miles,
        'total_time' : total_time
    }
    return render(request, 'dashboard/team_stats.html', context)

# Base dashboard view
def dashboard(request, rider=None):

    if rider:
        tm = Teammate.objects.get(pk=rider)
    elif not request.user.is_anonymous():
        tm = request.user
    else:
        return HttpResponseRedirect(reverse('dashboard:login'))

    # Retreive total miles
    rides = Ride.objects.filter(user_id__exact = tm).order_by('-date')
    miles = rides.aggregate(Sum('miles'))
    pace = rides.aggregate(Avg('pace'))
    duration = rides.aggregate(Sum('duration'))
    
    # Short Link - if it's there
    try:
      link = Link.objects.get(user_id__exact = tm)
    except ObjectDoesNotExist:
      # Return context
      context = {
          'miles': miles,
          'pace': pace,
          'duration': duration,
          'rides' : rides,
          'rider' : tm,
          'import_date' : date(2014,01,26),
      }


      return render(request, 'dashboard/index.html', context) 
    
    # Return context
    context = {
        'miles': miles,
        'pace': pace,
        'duration': duration,
        'rides' : rides,
        'rider' : tm,
        'link' : link,
        'import_date' : date(2014,01,26),
    }


    return render(request, 'dashboard/index.html', context)
    

def enter_gate(request):
    # Only execute login logic if data is posted
    if request.method == 'POST':
        # Set user variables
        username = request.POST.get('username', False)
        password = request.POST.get('password', False)
        # Authenticate the user
        user = authenticate(username = username, password = password)
        # If the user is a user
        if user is not None:
            if user.is_active:
                login(request, user)
                # First login
                tm = Teammate.objects.get(id__exact = request.user.id)
                if tm.first_login == True:
                    # Redirect to first_login page
                    return HttpResponseRedirect(reverse('dashboard:first_login'))
                else:
                    # Redirect straight to the dashboard
                    return HttpResponseRedirect(reverse('dashboard:dashboard'))
            # If the user isn't active
            else:
                # Return context error message
                context = {
                    'error_message': "You're not an active rider, man."
                }
                return render(request, 'dashboard/login.html', context)
        # If the user doesn't authenticate
        else:
            # Return context error message
            context = {
                'error_message': "Your username and password don't match!"
            }
            return render(request, 'dashboard/login.html', context)
    # If there's no POST data; just a normal login page
    else:
        # Return context w/ no error
        return render(request, 'dashboard/login.html', {})

# Logout view
def exit_gate(request):
    logout(request)
    return redirect('dashboard:dashboard')

# Change user's password
@login_required
def change_password(request):
    # If the form has been submitted
    if request.method == 'POST':
        # Check if the passwords match
        if request.POST['password1'] == request.POST['password2'] and request.POST['password2'] is not None:
            # Change the password
            u = Teammate.objects.get(id__exact = request.user.id)
            u.set_password(request.POST['password2'])
            u.save()
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        else:
           context = {
               'error_message': "Your passwords don't match!"
           }
           return render(request, 'dashboard/change_password.html', context)
    else: # First time visiting page
        return render(request, 'dashboard/change_password.html', {})

# Change user's password upon first login
@login_required
def first_login(request):
    # If the form has been submitted
    if request.method == 'POST':
        # Check if the passwords match
        if request.POST['password1'] == request.POST['password2'] and request.POST['password2'] is not None:
            # Change the password and user data
            u = Teammate.objects.get(id__exact = request.user.id)
            u.set_password(request.POST['password2'])
            u.email = request.POST['email']
            u.first_name = request.POST['first_name']
            u.last_name = request.POST['last_name']
            u.title = request.POST['title']
            u.route = request.POST['route']
            u.date_of_birth = request.POST['date_of_birth']
            u.first_login = False
            u.save()
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        else:
           context = {
               'error_message': "Your passwords don't match!"
           }
           return render(request, 'dashboard/first_login.html', context)
    else: # First time visiting page
        # Get teammate
        tm = Teammate.objects.get(id__exact = request.user.id)
        # Create context
        context = {
            'rider' : tm,
        }
        return render(request, 'dashboard/first_login.html', context)

templates/dashboard/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title> {% block title %} Texas 4000 Rider Management System | Dashboard {% endblock %}</title>
    {% load datetime_duration %}
    <!-- Stylesheets -->
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://s3.amazonaws.com/t4krms/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="//static.t4k2015.com/fixnav.css">
    <link rel="stylesheet" type="text/css" href="//static.t4k2015.com/datepicker3.css">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href={% url 'dashboard:dashboard' %}>Texas 4000 RMS</a>
        </div>
        <div class="navbar-collapse collapse">
          {% block navbar %}
          <ul class="nav navbar-nav">
            <li><a href="{% url 'dashboard:dashboard' %}">Home</a></li>
            {% if not user.is_anonymous %}
		    <li class="dropdown">
		      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Fitness <b class="caret"></b></a>
		      <ul class="dropdown-menu">
		  	    <li><a href="{% url 'fitness:rides' %}">Rides</a></li>
                <li><a href="{% url 'fitness:log' %}">Log Ride</a></li>
		      </ul>
		    </li>
		    <li class="dropdown">
		      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tools <b class="caret"></b></a>
		      <ul class="dropdown-menu">
				<li class="dropdown-header">Short Link</li>
				<li><a href="{% url 'links:settings' %}">Settings</a></li>
		      </ul>
		    </li>
            {% endif %}
          </ul>
		  <ul class="nav navbar-nav navbar-right">
		    {% if not user.is_anonymous %}
		    {% if user.is_staff %}
		    <li><a href="{% url 'admin:index' %}">Admin</a><li>
		    {% endif %}
		    <li><a href="{% url 'dashboard:team_stats' %}">Team Stats</a></li>
		    <li><a href="{% url 'dashboard:logout' %}">Logout</a></li>
		    {% endif %}
		  </ul>
          {% endblock %}
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
	
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//static.t4k2015.com/bootstrap-datepicker.js"></script>
    <script>
      $(document).ready(function () {
        $('#date').datepicker({
          format: "yyyy-mm-dd",
          todayHighlight: true,
          autoclose: true,
          startDate: '-7d',
          endDate: '0d'
        })
      })
    </script>
	{% block additional_scripts %} {% endblock %}
  </body>
</html>

templates/dashboard/change_password.html
{% extends "base.html" %}

{% block content %}
<div class="page-header">
  <h1>Change Password</h1>
</div>
{% if error_message %}
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p>{{ error_message }}</p>
</div>
{% endif %}
<form class="form-horizontal" role="form" method="post" action="{% url 'dashboard:change_password' %}">
  {% csrf_token %}
  <div class="form-group">
    <label for="password1" class="col-sm-4 control-label">New Password</label>
    <div class="col-sm-5">
      <input type="password" class="form-control" name="password1" id="password1" required>
    </div>
  </div>
  <div class="form-group">
    <label for="password2" class="col-sm-4 control-label">Confirm New Password</label>
    <div class="col-sm-5">
      <input type="password" class="form-control" name="password2" id="password2" required>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-5">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Change it!</button>
    </div>
  </div>
</form>
{% endblock %}

templates/dashboard/first_login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Texas 4000 Rider Management System | First Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Stylsheets -->
    <link rel="stylesheet" href="https://s3.amazonaws.com/t4krms/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="//static.t4k2015.com/signin.css">
    <link rel="stylesheet" type="text/css" href="//static.t4k2015.com/datepicker3.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
	<style>
	body {
	  background-image: url('//static.ethanperez.com/pic5.jpg');
		background-repeat: no-repeat;
    background-size: cover;
	  background-color: #cccccc;
	}
  .panel {
    background-color: rgba(255, 255, 255, 0.5);
  }
  .form-signin input[type="text"] {
  margin-bottom: 10px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  }
  .form-signin input[type="email"] {
  margin-bottom: 10px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  }
  .form-signin select {
  margin-bottom: 10px;
  border-bottom-left-radius: 0;
  border-bottom-right-radius: 0;
  }
	</style>
  </head>
  <body>
    <div class="container">
      {% if error_message %}
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>{{ error_message }}</p>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-md-4 col-md-offset-4 panel panel-default">
          <form class="form-signin" role="form" method="post" action="{% url 'dashboard:first_login' %}">
            {% csrf_token %}
            <h2 class="form-signin-heading">First Time Set-Up</h2>
            <p class="text-center">Congratulations on your first login to RMS!</p> 
            <p class="text-center">Before you can get started, make sure all your personal information is correct. You will also need to set your password before you can continue.</p>
            <legend class="text-center">Set Password</legend>
              <input type="password" class="form-control" placeholder="Password" name="password1" required autofocus>
              <input type="password" class="form-control" placeholder="Confirm password" name="password2" required>
            <legend class="text-center">Personal Information</legend>
              <input type="email" class="form-control" value="{{ rider.get_email }}" name="email" placeholder="Email" required>
              <input type="text" class="form-control" value="{{ rider.first_name }}" name="first_name" placeholder="First Name" required>
              <input type="text" class="form-control" value="{{ rider.last_name }}" name="last_name" placeholder="Last Name" required>
              <input type="text" class="form-control" placeholder="Date of birth" name="date_of_birth" id="date_of_birth" pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])" required title="YYYY-MM-DD format">
            <legend class="text-center">Team Information</legend>
              <input type="text" class="form-control" placeholder="Team title" name="title" required>
              <select class="form-control" id="route" name="route">
                <option value="sierra">Sierra</option>
                <option value="rockies">Rockies</option>
                <option value="ozarks">Ozarks</option>
              </select>
              <button class="btn btn-lg btn-info btn-block" type="submit">Update Information</button>
          </form>
        </div>
        </div>
      </div>
    </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//static.t4k2015.com/bootstrap-datepicker.js"></script>
    <!-- Script for datepicker -->
    <script>
      $(document).ready(function () {
        $('#date_of_birth').datepicker({
          format: "yyyy-mm-dd",
          autoclose: true,
          endDate: '0d',
        })
      })
    </script>
  </body>
</html>

templates/dashboard/index.html
{% extends "base.html" %}

{# TODO: I don't understand why I have to load it again =/ #}
{% load datetime_duration %}

{% block content %}
{% if success_message %}
<div class="alert alert-success alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <p>{{ success_message }}</p>
</div>
{% endif %}

<div class="page-header">
  <h1>{{ rider.get_full_name }}'s Dashboard</h1>
</div>
<div class="row">
  <div class="col-sm-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Basic Information</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">Name: {{ rider.get_full_name }}</li>
        <li class="list-group-item">Email: {{ rider.get_email }}</li>
        <li class="list-group-item">Title: {{ rider.get_title }}</li>
        <li class="list-group-item">Route: {{ rider.route|title }}</li>
        <li class="list-group-item">Date of Birth: {{ rider.get_dob }}</li>
      </ul>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Fitness Summary</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">Total Miles: {{ miles.miles__sum }}</li>
        <li class="list-group-item">Total Time Ridden: {{ duration.duration__sum|timedelta }}</li>
        <li class="list-group-item">Average Pace: {{ pace.pace__avg }} {% if pace.pace__avg%}mph{% endif %}</li>
      </ul>
    </div>
  </div>
  <div class="col-sm-4">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Short Link Summary</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item">Kintera Link: t4k2105.com/donate/{{ link.url }}</li>
        <li class="list-group-item">Profile Link: t4k2105.com/rider/{{ link.url }}</li>
        <li class="list-group-item">Total Clicks: {{ link.clicks }}</li>
		<li class="list-group-item">Last Click: {{ link.last_click }}</li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}

templates/dashboard/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Texas 4000 Rider Management System | Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Stylsheets -->
    <link rel="stylesheet" href="https://s3.amazonaws.com/t4krms/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="//static.t4k2015.com/signin.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
	<style>
	body {
	  background-image: url('//static.ethanperez.com/pic1.jpg');
		background-size: cover;
		background-repeat: no-repeat;
	  background-color: #cccccc;
	}

  .panel {
    background-color: rgba(255, 255, 255, 0.5);
  }
	</style>
  </head>
  <body>
    <div class="container">
      {% if error_message %}
      <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <p>{{ error_message }}</p>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-md-4 col-md-offset-4 panel panel-default">
          <form class="form-signin" role="form" method="post" action="{% url 'dashboard:login' %}">
            {% csrf_token %}
            <h2 class="form-signin-heading">Texas 4000 RMS</h2>
            <input type="text" class="form-control" placeholder="Email address" name="username" required autofocus>
            <input type="password" class="form-control" placeholder="Password" name="password" required>
            <button class="btn btn-lg btn-info btn-block" type="submit">Sign in</button>
          </form>
        <div class="row text-center">
          <a href="#">Forgot Password?</a>
          <p></p>
        </div>
        </div>
      </div>
    </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </body>
</html>

templates/dashboard/team_stats.html
{% extends "base.html" %}

{# TODO: I don't understand why I have to load it again =/ #}
{% load datetime_duration %}

{% block content %}
<div class="page-header">
  <h1>Team Summary</h1>
</div>
<div class="row">
  <div class="col-sm-6">
    <h3> Total Miles Ridden: {{ total_miles }} </h3>
    <h3> Total Time Ridden: {{ total_time|timedelta }} </h3>
  </div>
</div>

<div>
<h1> Riders </h1>
<hr />
</div>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th> Name </th>
        <th> Miles Ridden </th>
        <th> Time Ridden </th>
      </tr>
    </thead>
    <tbody>
      {% for rider in riders %}
      <tr>
        <td> <a href={% url 'dashboard:dashboard' rider.pk %}> {{ rider.get_full_name }}</a> </td>
        <td> {{ rider.total_miles }} </td>
        <td> {{ rider.total_time|timedelta}} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}